repos:
  - repo: https://github.com/thetestlabs/psscriptanalyzer-pre-commit
    rev: v1.0.1 # Use the latest version
    hooks:
      # Lint PowerShell files (show warnings and errors)
      - id: psscriptanalyzer
        args: ["--severity", "Warning"]

      # Format PowerShell files
      - id: psscriptanalyzer-format
