repos:
  - repo: https://github.com/thetestlabs/psscriptanalyzer-pre-commit
    rev: v1.0.11 # Use the latest version
    hooks:
      # Lint PowerShell files (show all severity levels)
      - id: psscriptanalyzer
        args: ["--severity", "All"]

      # Format PowerShell files
      # - id: psscriptanalyzer-format
