repos:
  - repo: https://github.com/thetestlabs/py-psscriptanalyzer
    rev: v0.3.1 # Use the latest version
    hooks:
      - id: py-psscriptanalyzer # Lint PowerShell files
        args: ["--severity", "Warning"] # Show Warning and Error level issues
      - id: py-psscriptanalyzer-format # Format PowerShell files

  # Optional: Add other pre-commit hooks as needed
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
