name: PowerShell Formatting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  format-powershell:
    name: Format PowerShell Files
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install PowerShell
      run: |
        sudo apt-get update
        sudo apt-get install -y wget apt-transport-https software-properties-common
        wget -q "https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb"
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get update
        sudo apt-get install -y powershell
    
    - name: Install py-psscriptanalyzer
      run: |
        python -m pip install --upgrade pip
        pip install py-psscriptanalyzer
    
    - name: Check formatting issues
      run: |
        echo "Checking for formatting issues..."
        # Run formatting check first to identify files with issues
        find . -name "*.ps1" -o -name "*.psm1" | xargs py-psscriptanalyzer --severity Information || true
      
    - name: Format PowerShell files
      run: |
        echo "Formatting PowerShell files..."
        # Format all PowerShell files
        find . -name "*.ps1" -o -name "*.psm1" | xargs py-psscriptanalyzer --format
      
    - name: Check for changes
      id: git-check
      run: |
        if [[ -n $(git status -s) ]]; then
          echo "has_changes=true" >> $GITHUB_OUTPUT
        else
          echo "has_changes=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit formatted files
      if: steps.git-check.outputs.has_changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Apply PowerShell formatting [skip ci]"
        
    - name: Create Pull Request
      if: steps.git-check.outputs.has_changes == 'true' && github.event_name == 'workflow_dispatch'
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ github.token }}
        commit-message: Apply PowerShell formatting
        title: 'Auto-format PowerShell files'
        body: |
          This PR applies automatic formatting to PowerShell files using PSScriptAnalyzer.
          
          *Auto-generated by the PowerShell Formatting workflow.*
        branch: auto-format-powershell
        base: ${{ github.ref_name }}
